Repository Brightspace/d2l-rubric, pull requests merged in 2021-03, with the labels that each got.

#737 DE42693 - Fix for Rubric Add Feedback (20.21.3)
  d2l-rubric-criteria-group.js
Labels: bug

#736 DE42692 - Fix for Rubric Add Feedback (20.21.4)
  d2l-rubric-criteria-group.js
Labels: bug

#739 Add preserve symlink flag
  package.json
Labels: enhancement

#747 Fix dialog width issues
  editor/d2l-rubric-criterion-editor.js
Labels: bug

#746 [20.21.3] Error logging fixes/improvements
  d2l-rubric.js
  editor/d2l-rubric-editor.js
  editor/d2l-rubric-structure-editor.js
  telemetry-behavior.js
Labels: bug, enhancement

#745 Error logging fixes/improvements
  d2l-rubric.js
  editor/d2l-rubric-editor.js
  editor/d2l-rubric-structure-editor.js
  package-lock.json
  package.json
  telemetry-behavior.js
Labels: bug, enhancement

#750 US114403 - Pass down activity alignment list type name and title
  build/lang/ar.js
  build/lang/cy.js
  build/lang/da.js
  build/lang/de.js
  build/lang/en.js
  build/lang/es-es.js
  build/lang/es.js
  build/lang/fr-fr.js
  build/lang/fr.js
  build/lang/ja.js
  build/lang/ko.js
  build/lang/nl.js
  build/lang/pt.js
  build/lang/sv.js
  build/lang/tr.js
  build/lang/zh-tw.js
  build/lang/zh.js
  editor/d2l-rubric-criterion-editor.js
  lang/ar.json
  lang/cy.json
  lang/da.json
  lang/de.json
  lang/en.json
  lang/es-es.json
  lang/es.json
  lang/fr-fr.json
  lang/fr.json
  lang/ja.json
  lang/ko.json
  lang/nl.json
  lang/pt.json
  lang/sv.json
  lang/tr.json
  lang/zh-tw.json
  lang/zh.json
  package-lock.json
  package.json
Labels: enhancement
